-- Migrazione 0007: tabella testi_ui per testi i18n modificabili dal DB
-- Ogni riga = una chiave + una lingua. PK composta (chiave, lang).
-- Il codice usa: DB sovrascrive hardcoded, fallback al codice se chiave mancante.

CREATE TABLE IF NOT EXISTS testi_ui (
  chiave TEXT NOT NULL,
  lang   TEXT NOT NULL CHECK(lang IN ('it','en','fr','es','de')),
  valore TEXT NOT NULL DEFAULT '',
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (chiave, lang)
);

-- ─── INSERT testi IT ──────────────────────────────────────────────────────────
-- Solo lingua IT (opzione A). Le altre lingue restano hardcoded nel codice.

INSERT OR IGNORE INTO testi_ui (chiave, lang, valore) VALUES
('title',               'it', 'Sindrome ReNU Italia APS'),
('subtitle',            'it', 'Insieme, facciamo la differenza'),
('tagline',             'it', 'Una condizione genetica di nuova identificazione. Uno sforzo di ricerca coordinato a livello globale.'),
('hero_text',           'it', 'La sindrome di ReNU è una condizione complessa che coinvolge ogni giorno <strong>bambini, ragazzi e famiglie</strong>. Questo spazio nasce per offrire informazioni chiare, orientamento concreto e la forza di una comunità che condivide lo stesso percorso.'),
('hero_desc',           'it', 'La Sindrome ReNU è causata da varianti patogene del gene RNU4-2. Attualmente sono <strong>~250 i casi accertati nel mondo</strong> (12-14 in Italia). Le varianti patogene si concentrano in soli <a href="https://rarediseasegenomics.org/blog/saturation-genome-editing-of-rnu4-2" target="_blank" class="text-sky-200 hover:underline font-semibold">13 posizioni</a> degli oltre 3 miliardi di paia di basi del genoma! Siamo qui per <strong>supportare le famiglie italiane</strong> e offrire un aiuto concreto ai bambini ReNU.'),
('btn_diagnosis',       'it', 'DONA ORA – SOSTIENI LE FAMIGLIE RENU'),
('btn_diagnosis_sub',   'it', 'Ogni contributo fa la differenza. Grazie.'),
('btn_info',            'it', 'VUOI MAGGIORI INFORMAZIONI? CLICCA QUI'),
('btn_info_sub',        'it', 'Contattaci per informazioni sulla Sindrome ReNU'),
('section_map_title',   'it', 'Mappa Famiglie'),
('section_map_desc',    'it', 'Aggiungi il tuo familiare con Sindrome ReNU alla mappa mondiale per aumentare la consapevolezza e la forza della comunità.'),
('section_awareness_title', 'it', 'Aumenta la Consapevolezza'),
('section_awareness_desc',  'it', 'Diffondi la conoscenza sulla Sindrome ReNU in Italia e aiuta a raggiungere le famiglie ancora non diagnosticate.'),
('section_science_title',   'it', 'Comitato Scientifico'),
('section_science_desc',    'it', 'Il Comitato Scientifico garantisce rigore e autorevolezza scientifica. Collabora con famiglie e professionisti per orientamenti pratici.'),
('section_research_title',  'it', 'Approfondimenti'),
('section_research_desc',   'it', 'Esplora le risorse scientifiche, le terapie di supporto e le iniziative di ricerca sulla Sindrome ReNU.'),
('section_info_title',      'it', 'Cos''è ReNU'),
('section_info_desc',       'it', 'Scopri cos''è la Sindrome ReNU, le caratteristiche cliniche e le informazioni genetiche aggiornate.'),
('section_parents_title',   'it', 'Rete Genitori Italiani'),
('section_parents_desc',    'it', 'La rete dei genitori italiani è un punto di riferimento per chi desidera sentirsi meno solo, condividere domande, esperienze e piccole conquiste del quotidiano.'),
('section_donations_title', 'it', 'Donazioni'),
('section_donations_desc',  'it', 'Il tuo supporto ci permette di promuovere la ricerca, costruire la comunità e offrire un aiuto concreto alle famiglie ReNU in Italia.'),
('about_title',             'it', 'Cos''è la Sindrome ReNU?'),
('about_gene',              'it', 'La sindrome di ReNU (RNU4-2) è una rara condizione genetica del neurosviluppo, identificata di recente dalla ricerca scientifica internazionale. È associata a variazioni del gene RNU4-2, coinvolto in un processo essenziale per il corretto funzionamento delle cellule, chiamato splicing dell''RNA. La sua descrizione scientifica è stata consolidata nel 2024 grazie a importanti studi internazionali.'),
('about_discovery',         'it', 'Scoperta di RNU4-2'),
('about_discovery_text',    'it', 'RNU4-2 è stata identificata nell''ottobre 2024 come una delle principali cause genetiche di disturbi rari del neurosviluppo, con una prevalenza stimata di circa 1 su 35.000 nati vivi.'),
('about_features_title',    'it', 'Caratteristiche della Sindrome ReNU'),
('about_brain',             'it', 'Anomalie cerebrali'),
('about_brain_items',       'it', 'Volume ridotto della materia bianca, ipoplasia del corpo calloso, ventricomegalia, mielinizzazione ritardata'),
('about_development',       'it', 'Disabilità intellettiva'),
('about_development_items', 'it', 'Ritardi nello sviluppo, limitazioni nel funzionamento intellettivo e nel comportamento adattivo'),
('about_seizures',          'it', 'Epilessia'),
('about_seizures_items',    'it', 'Spasmi infantili, crisi focali e tonico-cloniche, crisi febbrili o stato epilettico'),
('about_vision',            'it', 'Problemi visivi'),
('about_vision_items',      'it', 'Ipoplasia del nervo ottico, CVI (compromissione visiva corticale), strabismo, nistagmo'),
('about_face',              'it', 'Caratteristiche del viso'),
('about_face_items',        'it', 'Viso miopatico, epicanto, radice nasale larga, narici anteverse, grandi orecchie, guance piene'),
('about_muscle',            'it', 'Tono muscolare'),
('about_muscle_items',      'it', 'Ipotonia (basso tono muscolare) o debolezza muscolare'),
('about_mobility',          'it', 'Mobilità'),
('about_mobility_items',    'it', 'Ritardo nel cammino o incapacità di camminare'),
('about_growth',            'it', 'Crescita'),
('about_growth_items',      'it', 'Microcefalia, bassa statura, ipotiroidismo o deficit dell''ormone della crescita'),
('about_feeding',           'it', 'Alimentazione'),
('about_feeding_items',     'it', 'Difficoltà alimentari, scialorrea, stipsi, reflusso gastroesofageo'),
('about_communication',     'it', 'Comunicazione'),
('about_communication_items','it','Difficoltà di linguaggio (possono sviluppare comunicazione alternativa)'),
('about_bones',             'it', 'Problemi ossei'),
('about_bones_items',       'it', 'Bassa densità ossea, displasia dell''anca, fratture ricorrenti'),
('about_happy',             'it', 'Molte persone con Sindrome ReNU mostrano un temperamento felice, sono affettuose e amano le altalene, l''acqua, la musica e le routine.'),
('about_diagnosis_note',    'it', 'In Italia, per diagnosticare RNU4-2 è necessario il Sequenziamento dell''Intero Genoma (WGS). Il WES non è in grado di rilevarlo!'),
('research_title',          'it', 'Approfondimenti'),
('research_intro',          'it', 'TU puoi far avanzare la ricerca verso opzioni di trattamento per ReNU!'),
('research_crid',           'it', 'Prima di iscriversi a qualsiasi ricerca, crea un <a href="https://thecrid.org/" target="_blank" class="text-yellow-300 hover:underline font-semibold">ID di Ricerca Clinica (CRID)</a>! Condividi il tuo CRID con ogni studio clinico a cui partecipi.'),
('research_priorities_title','it','Cosa è importante per la comunità RNU4-2?'),
('therapies_title',         'it', 'Terapie per la Sindrome ReNU'),
('therapies_intro',         'it', 'Ogni percorso terapeutico deve essere personalizzato sulla base dei bisogni del bambino o del ragazzo e condiviso con i professionisti di riferimento. In questa sezione raccogliamo alcune aree di intervento che possono sostenere sviluppo, autonomia, comunicazione e qualità della vita.'),
('therapies_note',          'it', 'Questo sito non approva né raccomanda terapie specifiche. Consultare sempre un medico.'),
('diagnosis_title',         'it', 'Dove fare il Test Diagnostico in Italia'),
('diagnosis_intro',         'it', 'Per ricevere informazioni sui centri diagnostici disponibili in Italia, contattaci.'),
('diagnosis_contact',       'it', 'Per informazioni sui centri WGS in Italia, scrivici a:'),
('community_title',         'it', 'Comunità ReNU Italia'),
('community_intro',         'it', 'ReNU Italia APS vuole essere uno spazio di incontro, ascolto e condivisione. La comunità nasce per mettere in relazione famiglie, promuovere il confronto tra esperienze e rendere più accessibili informazioni e contatti utili.'),
('community_network_it',    'it', 'Rete genitori italiani'),
('community_network_desc',  'it', 'La rete dei genitori italiani è un punto di riferimento per chi desidera sentirsi meno solo, condividere domande, esperienze e piccole conquiste del quotidiano.'),
('donations_title',         'it', 'Sostienici'),
('donations_intro',         'it', 'Il tuo supporto ci permette di promuovere la ricerca, costruire la comunità e offrire un aiuto concreto alle famiglie ReNU in Italia.'),
('donations_iban',          'it', 'IT18H0306909606100000416360'),
('donations_iban_label',    'it', 'Intestato a: Sindrome ReNU Italia APS'),
('contact_title',           'it', 'Contattaci'),
('contact_intro',           'it', 'Siamo a tua disposizione per qualsiasi informazione sulla Sindrome ReNU Italia.'),
('brochure_title',          'it', 'Media & Pubblicazioni'),
('brochure_intro',          'it', 'In questa sezione raccogliamo video, articoli scientifici, materiali divulgativi e brochure utili ad approfondire la conoscenza della sindrome di ReNU.'),
('science_title',           'it', 'Comitato Scientifico'),
('science_intro',           'it', 'Il Comitato Scientifico di Sindrome ReNU Italia APS svolge un ruolo fondamentale nel garantire che l''Associazione operi con rigore, autorevolezza e coerenza con le migliori evidenze scientifiche disponibili. Collabora con i soci, le famiglie e i professionisti per tradurre la conoscenza scientifica in orientamenti pratici, strumenti di supporto e iniziative concrete a favore delle persone con Sindrome ReNU e delle loro famiglie.'),
('science_role1_title',     'it', 'Validazione dei Contenuti'),
('science_role1_desc',      'it', 'Revisione e validazione dei contenuti medico-scientifici del sito, dei materiali informativi e delle pubblicazioni dell''Associazione, garantendo accuratezza e aggiornamento continuo.'),
('science_role2_title',     'it', 'Supporto alla Diagnosi'),
('science_role2_desc',      'it', 'Collaborazione con i centri diagnostici italiani per facilitare l''accesso al Sequenziamento dell''Intero Genoma (WGS), unico strumento diagnostico affidabile per RNU4-2, e per costruire un percorso di presa in carico multidisciplinare.'),
('science_role3_title',     'it', 'Ricerca e Registro Pazienti'),
('science_role3_desc',      'it', 'Promozione e coordinamento di progetti di ricerca italiani, incluso il Registro Nazionale Pazienti ReNU, per contribuire alla comprensione della sindrome e allo sviluppo di future terapie.'),
('science_role4_title',     'it', 'Formazione e Sensibilizzazione'),
('science_role4_desc',      'it', 'Progettazione e diffusione di campagne rivolte ai pediatri, ai medici di base e agli specialisti, per ridurre i tempi di diagnosi e migliorare la qualità dell''assistenza.'),
('science_role5_title',     'it', 'Collegamento Internazionale'),
('science_role5_desc',      'it', 'Partecipazione alla rete scientifica internazionale ReNU, in collaborazione con ReNU Syndrome United (USA) e altri centri di ricerca europei, per condividere dati e avanzare la conoscenza sulla sindrome.'),
('science_members_title',   'it', 'I Membri del Comitato'),
('science_members_note',    'it', 'L''elenco dei membri del Comitato Scientifico sarà pubblicato non appena il processo di nomina sarà completato. Per collaborazioni scientifiche o per segnalare nuove pubblicazioni contattaci a presidenza@sindromerenu.it.'),
('science_cta',             'it', 'Collabora con noi'),
('coe_title',               'it', 'Centro di Eccellenza ReNU (COE)'),
('coe_desc',                'it', 'ReNU Syndrome United sta costruendo una rete globale di Centri di Eccellenza per collegare le famiglie di pazienti con team medici multidisciplinari di altissimo livello, dedicati alla ricerca e al trattamento della Sindrome ReNU.'),
('world_title',             'it', 'ReNU nel Mondo'),
('world_desc',              'it', 'Famiglie RNU4-2 sono state mappate in: Australia, Belgio, Brasile, Canada, Cina, Colombia, Repubblica Ceca, Danimarca, Inghilterra, Francia, Germania, Grecia, Hong Kong, Islanda, Irlanda, Israele, Italia, Giappone, Messico, Paesi Bassi, Nuova Zelanda, Irlanda del Nord, Norvegia, Palestina, Polonia, Romania, Russia, Arabia Saudita, Scozia, Corea del Sud, Spagna, Svezia, Svizzera, Turchia, Ucraina, Stati Uniti, Galles.'),
('footer_rights',           'it', '© 2026 Sindrome ReNU Italia APS. Tutti i diritti riservati.'),
('footer_partnership',      'it', 'In partnership con ReNU Syndrome United (USA)'),
('footer_tagline',          'it', 'Insieme, facciamo la differenza'),
('intl_network',            'it', 'Rete Internazionale');
